# general configuration
url: http://excentris.net
baseurl: ''

#setup
title:      XuXinxin's Personal site
tagline:    'Enjoy code and life'
description: "I'm keen on programming, especially Web design,with good command of <b>C++</b>,<b>PHP</b>,<b>HTML</b> and <b>CSS</b>."

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/me.jpg"
  # author will appear under the avatar (optional)
  author: "XuXinxin"
  # tagline will appear under the title (optional)
  tagline: "Go to <a href='/blog'>Blog</a> for touching me more "
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
